using System;
using UnityEngine;
using System.Collections.Generic;

[CreateAssetMenu(fileName = "WheelSpinConfig", menuName = "Scriptables/WheelSpin/ClientConfig")]
public class WheelClientConfigSO : ScriptableObject
{
    public float spinDuration;
    public int maxProgressLevel;
    public SpinRewardItemSO bombReward;
    public List<SpinRewardItemSO> allRewardItemList;
    public List<SpinMod> SpinMods;
    public List<SpinLevel> spinLevels;

    private void OnValidate()
    {
        for (var i = 0; i < SpinMods.Count; i++)
        {
            SpinMods[i].SyncName();
        }
        
        //AutoGenerate values for dummy data, set first3 from editor
        #region AutoGenerateData
        /*if (spinLevels == null)
            return;
        if (spinLevels.Count < 3)
            return;

        // Bronze: 0-24
        // Silver: 25-44
        // Gold:   45+
        
        SpinLevel bronzeTemplate = spinLevels[0];
        SpinLevel silverTemplate = spinLevels[1];
        SpinLevel goldTemplate   = spinLevels[2];
        
        spinLevels.Clear();

        for (int i = 0; i < maxProgressLevel; i++)
        {
            SpinLevel source;

            if (i < 25)
                source = bronzeTemplate;
            else if (i < 45)
                source = silverTemplate;
            else
                source = goldTemplate;

            var cloneSpinLevel = CloneSpinLevel(source);
            cloneSpinLevel.bombPossibility = Mathf.Lerp(0f, 0.7f, (float)i/maxProgressLevel);
            spinLevels.Add(cloneSpinLevel);
        }*/
        #endregion
    }
    private SpinLevel CloneSpinLevel(SpinLevel source)
    {
        return new SpinLevel
        {
            bombPossibility = source.bombPossibility,
            rewards = CloneRewards(source.rewards)
        };
    }

    private List<SpinRewardEntry> CloneRewards(List<SpinRewardEntry> source)
    {
        var list = new List<SpinRewardEntry>(source.Count);

        foreach (var r in source)
        {
            list.Add(new SpinRewardEntry
            {
                reward = r.reward,   // SO → shared
                amount = r.amount    // int → copy
            });
        }

        return list;
    }
}

[Serializable]
public struct SpinLevel
{ 
    [Range(0,1)]public float bombPossibility;
    public List<SpinRewardEntry> rewards;
}

[Serializable]
public class SpinRewardEntry
{
    [SerializeField,HideInInspector] public string name; //inspector name
    public SpinRewardItemSO reward;
    public int amount;
}

[Serializable]
public class SpinMod
{
    [SerializeField,HideInInspector] public string name; //inspector name
    public int levelModPattern;
    public int requiredRewardItemCount; //Must match with base image
    public string viewName;
    public Sprite baseSprite;
    public Sprite indicatorSprite;
    
    public void SyncName()
    {
        name = viewName;
    }
}